[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "cube_analysis"
version = "0.0.0"
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["./docs/requirements.txt"]}